# simple make file for chapter 12
12-16: 12-16.c csapp.o
	gcc -o 12-16 12-16.c csapp.o -pthread

12-17: 12-17.c csapp.o
	gcc -o 12-17 12-17.c csapp.o -pthread

12-19: 12-19.c csapp.o
	gcc -o 12-19 12-19.c csapp.o -pthread

rw-weak: rw-weak.c csapp.o
	gcc -o rw-weak rw-weak.c csapp.o -pthread

12-20: 12-20.c csapp.o
	gcc -o 12-20 12-20.c csapp.o -pthread

12-21: 12-21.c csapp.o
	gcc -o 12-21 12-21.c csapp.o -pthread

12-22: 12-22.c csapp.o
	gcc -o 12-22 12-22.c csapp.o -pthread





