# simple make file for chapter 12
12-16: 12-16.c csapp.o
	gcc -o 12-16 12-16.c csapp.o -pthread

12-17: 12-17.c csapp.o
	gcc -o 12-17 12-17.c csapp.o -pthread

12-19: 12-19.c csapp.o
	gcc -o 12-19 12-19.c csapp.o -pthread

rw-weak: rw-weak.c csapp.o
	gcc -o rw-weak rw-weak.c csapp.o -pthread

12-20: 12-20.c csapp.o
	gcc -o 12-20 12-20.c csapp.o -pthread

12-21: 12-21.c csapp.o
	gcc -o 12-21 12-21.c csapp.o -pthread

12-22: 12-22.c csapp.o
	gcc -o 12-22 12-22.c csapp.o -pthread

12-23: 12-23.c csapp.o
	gcc -o 12-23 12-23.c csapp.o -pthread

12-26: 12-26.c csapp.o
	gcc -o 12-26 12-26.c csapp.o -pthread

12-31: tfgets-main.o tfgets-proc.o csapp.o
	gcc -o 12-31 tfgets-main.o tfgets-proc.o csapp.o -pthread

12-32: tfgets-main.o tfgets-select.o csapp.o
	gcc -o 12-32 tfgets-main.o tfgets-select.o csapp.o -pthread

12-33: tfgets-main.o tfgets-thread.o csapp.o
	gcc -o 12-33 tfgets-main.o tfgets-thread.o csapp.o -pthread

tfgets-main.o: tfgets-main.c
	gcc -c tfgets-main.c

tfgets-proc.o: tfgets-proc.c
	gcc -c tfgets-proc.c

tfgets-select.o: tfgets-select.c
	gcc -c tfgets-select.c

tfgets-thread.o: tfgets-thread.c
	gcc -c tfgets-thread.c






