# simple make file for chapter 10
10-6: 10-6.c csapp.o
	gcc -o 10-6 10-6.c csapp.o -pthread

10-7: 10-7.c csapp.o
	gcc -o 10-7 10-7.c csapp.o -pthread

10-8: 10-8.c csapp.o
	gcc -o 10-8 10-8.c csapp.o -pthread

10-10: 10-10.c csapp.o
	gcc -o 10-10 10-10.c csapp.o -pthread