# simple make file for chapter 11
11-2: 11-2.c csapp.o
	gcc -o hex2dd 11-2.c csapp.o -pthread

11-3: 11-3.c csapp.o
	gcc -o dd2hex 11-3.c csapp.o -pthread

11-4: 11-4.c csapp.o
	gcc -o hostinfo 11-4.c csapp.o -pthread

tiny: tiny.c csapp.o
	gcc -o tiny tiny.c csapp.o -pthread

11-6: 11-6.c csapp.o
	gcc -o 11-6 11-6.c csapp.o -pthread

11-7: 11-7.c csapp.o
	gcc -o 11-7 11-7.c csapp.o -pthread

11-8: 11-8.c csapp.o
	gcc -o 11-8 11-8.c csapp.o -pthread

11-9: 11-9.c csapp.o
	gcc -o 11-9 11-9.c csapp.o -pthread

11-11: 11-11.c csapp.o
	gcc -o 11-11 11-11.c csapp.o -pthread

11-12: 11-12.c csapp.o
	gcc -o 11-12 11-12.c csapp.o -pthread


