# simple make file for chapter 11
11-2: 11-2.c csapp.o
	gcc -o hex2dd 11-2.c csapp.o -pthread

11-3: 11-3.c csapp.o
	gcc -o dd2hex 11-3.c csapp.o -pthread

11-4: 11-4.c csapp.o
	gcc -o hostinfo 11-4.c csapp.o -pthread

