# simple make file for chapter 12
12-35: 12-35.c csapp.o
	gcc -o 12-35 12-35.c csapp.o -pthread

12-36: 12-36.c csapp.o
	gcc -o 12-36 12-36.c csapp.o -pthread

12-37: 12-37.c csapp.o
	gcc -o 12-37 12-37.c csapp.o -pthread

12-38: 12-38.c csapp.o sbuf.o
	gcc -o 12-38 12-38.c csapp.o sbuf.o -pthread

sbuf.o: sbuf.c sbuf.h
	gcc -c sbuf.c





